apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-tier
  template:
    metadata:
      labels:
        app: web-tier
    spec:
      containers:
      - name: web-container
        image: 681947837266.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        ports:
        - containerPort: 3000
